    name: GitHub Classroom Workflow

    on: workflow_dispatch
    
    env:
        pull_req_url: 'https://github.com/QA-Fullstack-SDET/8-sdet-blc-Maxon3327'
        token: ${{github.event.client_payload.token_csrf}} 
        github_token: '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'
        task_id: ${{github.event.client_payload.task_id}} 
        adapter_url: ${{github.event.client_payload.adapter_url}}
        task_score: 50
        max_score: 100
        status: Done
  
    jobs:
      build:
        name: Classroom test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          
          - name: Setup Java JDK
            uses: actions/setup-java@v3
            with:
                distribution: 'corretto'
                java-version: '17'
          
          - name: Split PR Url
            uses: jungwinter/split@v2
            id: split
            with:
                msg: '${{env.pull_req_url}}'
                separator: '://'
          
          - name: Clone student repo
            run: |
                tree
                sudo git clone https://mekater1na:${{ env.github_token }}@${{ steps.split.outputs._1 }} student_work
                sudo chmod -R 777 ./student_work
                tree 
          
          - name: Gradle Build
            working-directory: student_work
            run: gradle build -Dfile.encoding=UTF-8
          
          - name: Gradle Test
            working-directory: student_work
            run: gradle test
            
          - name: Update score
            if: ${{ success() }}
            run: echo "task_score=100" >> $GITHUB_ENV
